### ISSUE TITLE
SPIKE: Product Perpetuals

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#100]
## The Spike

As a Frontend Team at Vega
We want to understand the **Product Perpetuals** feature that core are developing and build a shared understanding of the implications / opportunities this feature creates for our user journeys and ultimately frontend applications 
So that we can agree on, plan and execute the work effectively

## How we'll know we're done

- [x] A cross section of frontend (UX, Dev, QA) are up to speed with the feature that is being developed by Core
- [x] We have a x-function / platform agreement on what this feature will enable for our users from a frontend perspective across all of our apps and tools (and at a high level, how)
- [x] We have a clear agreement on relative priorities / sequences for these features
- [x] We have established a way to stay in regular communications with the Core Feature Team in order to:
    - Have visibility of progress
    - Understand and track dependencies
    - Collaborate on key technical directions / decisions that impact our ability to deliver the agreed features in the FE  

## Tasks

- [x] Assign 1 UX/Requirements Lead, 1 Dev and 1 QA as the team to collaborate on this spike (who will then become the experts in this feature for the frontend) team)
- [x] Team reads the spec and all other background reading (below)
- [x] Team is given an initial brief from the core feature team to understand the potential implications / opportunities 
- [x] Team sketches out a hypothesis of the user journeys / features this core feature represents for frontends (including the relative priorities / sequencing) 
- [x] Team presents the hypothesis and facilitates a discussion around it with the core feature team, FELT and ELT 
- [x] Team refines further the hypothesis and shares with the wider business on Slack for input and feedback
- [x] Team finalises and breaks the work down into tickets for the appropriate project teams boards
- [x] Team defines and shares a target delivery plan that would enable the feature to be delivered in line with the core plan
- [x] Team rep participates in FE project team planning to represent the work, ensure it is understood and planned effectively
- [x] Team rep participates in core project team forums (TBC) to help maintain alignment and manage dependencies    

## Background Reading

- [Core Roadmap Feature Ticket](https://github.com/vegaprotocol/roadmap/issues/15)
- Frontend Roadmap Feature Ticket (TBC)
- [Core Feature Spec](https://github.com/vegaprotocol/specs/issues?q=label%3A%22product+perpetuals%22) 
- Core Feature Team:
    - TBC
- List of core tickets:
  - Dev Implementation: TBC
  - https://github.com/vegaprotocol/vega/issues/8369
  - https://github.com/vegaprotocol/system-tests/issues/532
