### ISSUE TITLE
Linking to Console from other Vega dapps

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#106]
Some of this at least might be swept up as part of the [onboarding challenge](https://github.com/vegaprotocol/ux-and-visual-design/issues/114)

## Story

As a Vega user
I want to be able to see a link to the Console trading dapp from any other Vega dapp
So that I know it exists and can get there easily

## Acceptance Criteria (TBC)

- [ ] The link is easy to find
- [ ] The link does not feel promotional in nature and is less annoying that the announcement banner 😆 
- [ ] The link is available (in a consistent way ?) on Governance, Block Explorer, Browser Wallet and Desktop Wallet(?), Docs(?)  

Deep linking too i.e to a market from a relevant transaction
Finding  transactions in explorer from console
Yes there is something to think about scalability to handle when there is more than one app for each use case 

## Tasks

- [ ] Explore and sketch solution x-platform
- [ ] Review and refine with stakeholders
- [ ] Create tickets and prioritise for the relevant project teams 

## Notes

https://vegaprotocol.slack.com/archives/C8WS7M50E/p1684862516953059
