### ISSUE TITLE
Network treasury view

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#111]
## Story

As a user
I want to see how the network treasury is currently distributed for each asset type
So that I understand the current governance of treasury funds and can use this to inform any future governance transfer proposals 

## Acceptance Criteria

- [ ] I can see how much is in treasury, insurance pool, margin accounts, general accounts, how much in reward pools
- [ ] There is a way to see how the treasury is currently distributed per asset 
- [ ] I can see a total TVL of all accounts everywhere

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

We want to use the existing [asset view](https://explorer.vega.xyz/assets/bf1e88d19db4b3ca0d1d5bdb73718a01686b18cf731ca26adedf3c8b83802bba)

All we should need to do is add lines to this for each of the new accounts that Zohar has created.

```
{
  assetsConnection {
    edges {
      node {
				name
        status
        globalRewardPoolAccount{
          balance
        }
        globalInsuranceAccount {
          balance
        }
        networkTreasuryAccount {
          balance
        }
      }
    }
  }
}
```
