### ISSUE TITLE
Update "market proposals" forum subcategory to include spots

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/ux-and-visual-design#113]
## The Chore

We need to update the Market Creation sub category on the forum to cover spot markets

## Tasks

- [x] Update guide to creating market proposals to include links to relevant docs and tutorials regarding spot markets
  - [x] new spot market
  - [x] amend spot market
  - [ ] update market state (also used for futures markets)
- [ ] Ensure the difference between futures market proposals and spot market proposals is clear ( new futures market is just a "new market" proposal, while a new spot market is a "new _spot_ market" proposal. Users must understand that the language treats futures as the default type of market)
- [ ] Add spot market details to the existing template for proposal forum posts

### [Guide to market proposals](https://community.vega.xyz/t/guide-to-market-proposals/3978)

<img width="811" alt="image" src="https://github.com/vegaprotocol/ux-and-visual-design/assets/1080322/91c4f18f-2967-4e4b-b954-219d20845525">

**Comment by JonRay15** [comment]
Two approaches here 

Ideallly, no change, stick with Create Market and Update Market and just make the template cover everything. 

If this is too painful due to the differing nature of the market proposals then the below would be acceptable:

- New future market
- New perps market
- New spot market
- Update existing market

**Comment by JonRay15** [comment]
Have done the essential here .... wont do more
