### ISSUE TITLE
Onboarding challenge

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#114]
## Story

We need to

- [x] Consider all the branches (Console, Website, Desktop wallet, Browser wallet, chrome store...)
- [x] Identify the "ideal" experience and what we're missing from knowing nothing about trading on vega to being able to trade on vega (you have a wallet, you've deposited assets)
- [x] Fill in the gaps to get to the "next step" e.g. in the wallet you don't have assets yet here's how to add assets, or now you've got a wallet want to trade: launch console, want to participate in governance: launch governance etc.
- [x] Identify any gaps between "Vega" touchpoints that need more support e.g. avoiding download antivirus style popups / setting expectations for what you'll see
- [x] Break up the work in a pragmatic way to prioritise 
- [x] Inform planning of the next steps of browser wallet (we've planning next week anyway) with this information

https://miro.com/app/board/uXjVM2wamp8=/?share_link_id=154780738970

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
