### ISSUE TITLE
Referral programme and volume discount proposals on Governance Proposals Category on Forum

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#122]
## The Chore

We need to add a new sub category or "home" on the forum for Update Referral Programme Proposals AND UpdateVolumeDiscountProgram proposals to be covered

## Tasks

- [ ] Create new sub category / structure for Update Referral Programme Proposals and Update Volume Discount Program Proposals under the existing Governance Proposals category
- [ ] Create guides to creating proposals to update referral programme and update volume discount programme proposals including links to relevant docs and tutorials etc.
- [ ] Include a template for to use for proposal forum posts

## Additional details / background info

<img width="1165" alt="Screenshot 2023-06-16 at 16 50 48" src="https://github.com/vegaprotocol/ux-and-visual-design/assets/47143694/1239d1dc-6c86-47b1-85f5-b8053e1c6f68">
<img width="1165" alt="Screenshot 2023-06-16 at 16 51 31" src="https://github.com/vegaprotocol/ux-and-visual-design/assets/47143694/251b62c5-bb0e-4b32-8dd1-16923c469258">
<img width="1135" alt="Screenshot 2023-06-16 at 16 51 43" src="https://github.com/vegaprotocol/ux-and-visual-design/assets/47143694/e7417bf8-6f54-49f4-95af-8e53bd1f6e21">

**Comment by JonRay15** [comment]
We wont do this ... we're more likely to remove all the subcategories since it makes it harder to track things... so I certainly wont be making an effort to add more categories for very rarely used things.
