### ISSUE TITLE
Align language / data where it makes sense between console + LP dashboard

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#14]
## The Chore

Frontend have just introduced improvements / data into a liquidity provider view - this may / may not inform the work we are doing in the LP dashboard.

## Tasks

- [ ] Review LP view in console
- [ ] Compare against what we've planned / sketched for the LP dashboard
- [ ] List out what we'd change to align the two and create / update issues where necessary

## Additional details / background info
See live example in https://console.fairground.wtf/liquidity/20026c62ff1445884ef47c7d6b10681b07317746997bbfa53ad4cd0e27da16eb
