### ISSUE TITLE
Acceptance criteria for `7003-MORD` Manage my orders

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#16]
## The Chore

To create a set of Acceptance criteria for Vega user interfaces for frontend end to end system tests to be written and run against, and reported on by [approbation](https://github.com/vegaprotocol/approbation) to assess test coverage (and therefore confidence).

This first cut of A/C for end to end tests should focus on ensuring the features and functionality we have today is trading ready.

## Tasks

- [ ] Write 'em
- [ ] get 'em reviewed
- [ ] get 'em merged
- [ ] Point QA at 'em

## Link to user interface A/C in specs repo and related PRs

https://github.com/vegaprotocol/specs/tree/master/user-interface

https://github.com/vegaprotocol/specs/pull/1139
https://github.com/vegaprotocol/specs/pull/1181
https://github.com/vegaprotocol/specs/pull/1223
