### ISSUE TITLE
Google slides look and feel for upcoming conference

### ISSUE THREAD

**Issue by bigfandavid** [vegaprotocol/ux-and-visual-design#20]
## The Chore

David, Klaus, Tom and Nissa need a pre-set deck of slides (provided by the conference organisers) designing to be as close to the Vega brand as possible.

## Tasks

- [ ] David S/Tom to fill the Google Slides doc with content
- [ ] David R to then adjust the look and feel and design in background images to align with Vega brand
- [ ] David S/Tom/Nissa to feedback and adjust any content
- [ ] David R to make any last-minute design tweaks

## Additional details / background info

Needs to be completed around 11th October. David S / Tom need a week from now (28th Sep) to bring together content.

Presentation (working doc) can be found here: https://docs.google.com/presentation/d/1_RIdyJUOGS73dL3LERR3OtCKPmnN1udXvz1kss3OZ_w/edit#slide=id.p2
