### ISSUE TITLE
Bring vega.xyz websites design work into the design system

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#3]
As a design team
We want the Vega website designs to be part of the design system
So that all design work for Vega is in one place, easily findable and as reusable as possible

**Acceptance Criteria**

- All design work for the vega.xyz website (including work in progress) is in one Figma file/project (the design system) 
- Everyone in the Frontend Engineering team has read access to this file and the URL is shared somewhere public (i.e. bookmarked in relevant Slack channels or linked to from the relevant repos readme etc. 
- Everyone on the UX & Design team have edit access to the design system and understands the process for creating new designs (i.e. all work to be done in this file/project, not creating multiple different files etc.)

**Tasks**

- [ ] Can we work out what is involved here and what you've already done @joellecharlotte ?
- [ ] Specify titles / typography styles H1 - 6 etc.
- [ ] Identify any stories / tasks required for development and add to backlog
