### ISSUE TITLE
Thought leadership blog post

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#4]
**Tasks**

- [X] Interview with Barney and Nissa to extract information
- [X] Write piece
- [X] Get feedback from Nissa 
- [X] Make revisions
- [ ] Get feedback from Barney

Blog post: The unpredictable impacts of daring to evolve and innovate (in Web3 and beyond)

DRAFT: https://docs.google.com/document/d/1h78jMTsRZkc1Ba_a9r3tWBQdgpk8LklWhhuUR0qlM_0/edit

**Comment by pennyandrews** [comment]
This is on hold indefinitely
