### ISSUE TITLE
Create Vega branded slide template

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#5]
Klaus made a request for this
Nissa asked to be involved in the discussion about what their requirements might be and what they would use them for etc.

David comfortable creating slide templates in keynote but not powerpoint or google slides but we can get someone else in to do that if needed

**Tasks**

- [X] Take a brief for what they need
- [X] First draft of slides
- [ ] Feedback from Nissa and Klaus (requested)
- [ ] Implement feedback
- [ ] Sign off
- [ ] Create PowerPoint version
