### ISSUE TITLE
Propose new / update asset guide + template on the forum

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#54]
## Story

As a forum user
I want to know what I need to share to sense check my proposal on the forum 
So that I have the best chance of having my proposal voted on

## Acceptance Criteria

- [ ] I can see guide(s) to asset proposals to create a new asset and to update an existing asset on the forum
- [ ] I can start from a template topic for new asset proposals and update proposals on the forum

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
