### ISSUE TITLE
User research approach and planning

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#57]
As a team 
We want to establish a regular cadence of user research activities
So that we can identify things we need to improve 

## Tasks

- [x] Understand what we are already doing (Incentives, keeping an eye on the user feedback board, anything else? Otherwise we have done ad hoc research for specific tasks) 
- [ ] Jump on next incentive as a pilot / poc / experiment
- [x] Design an approach to get more user insights into this team and product backlogs 
- [x] Work out where our participants might come from, how we find the right balance of keen community members and people who might actually trade with us! Is there a combination of community based research and research with traders outside of Vega for example
- [ ] Work out how we can expose the product teams themselves to the research (not just the findings)
- [ ] Find the balance between project specific research i.e. validating app features v broader user journey type stuff to identify things we are missing
- [ ] Review / share with the team 

## Background

* We need some regular trading related research set up once you can trade - looking at improving the existing product AND what we should be doing in the future
* Some research was done on other trading platform use in the past
* We need to decide whether the rolling regular research is what we feed in project specific research or if that's separate
* To consider surveying and responding to industry developments (to help generate quality thought leadership) as part of this too
