### ISSUE TITLE
Products available to trade (FE tickets defined)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#59]
## Challenge

Can we make it clear to users what  products  are available to trade on Vega i.e. futures, other derivatives options, forwards, swaps + spots, perpetuals

## Tasks

- [x] Prepare X-platform session / Explore and sketch
- [x] Run X-platform session 
- [x] Create backlog tickets for relevant frontends
