### ISSUE TITLE
Trading first use

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#60]
## Challenge

Can we improve the first use experience of trading to get people up and running more quickly and easily e.g. in context links / guidance - make your first deposit - whilst making it clear what markets are live

## Tasks

- [x] Get input from x-platform session 
- [x] Sketch out the to-be flow
- [x] Share on x-platform slack channel for feedback
- [x] Iterate
- [x] Create tickets for relevant frontends 

Probably makes sense to refine https://github.com/vegaprotocol/vega.xyz/issues/246 as part of working this out

## Sketch

Miro:- https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764535554690708&cot=14
