### ISSUE TITLE
Becoming a validator

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#71]
## Challenge 

Can we make the process of becoming a validator, the minimum requirements for doing so, and the selection mechanics clear to the network.

## Tasks 

- [x] Share current status of validator content 
- [x] Identify if we're missing any pieces for an MVP (what are we doing about the forum) 
- [x] Create tickets for any remaining work
