### ISSUE TITLE
Epic: Oracle proofs

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/ux-and-visual-design#79]
## Story

As a market maker
I want voters to trust the oracle for my market
So they are more likely to vote in favour

## Acceptance Criteria

- [ ] I can provide proofs of ownership for accounts (e.g. Twitter, Facebook) associated with an oracle
- [ ] The option to provide proofs is evident in the market creation journey
- [ ] I can find oracle details and proofs for each market (on console) and market proposal (on the token site)
- [ ] I can independently verify those proofs

## Tasks

- [x] Define the list of channels we will accept proofs on
- [x] Sketch the journey for providing and verifying those proofs, considering all touchpoints, e.g.:
  - generating signed messages
  - uploading proofs to the repo for oracle metadata
  - verifying a proof
  - vega.xyz market creation page?
  - token site market creation process?
  - guide in docs?
- [x] Spec structure and content for the proofs file which will be uploaded to the repo (e.g. is it just a list of links? are there inline comments to give guidance?)
- [x] Stakeholder review and design critique of the journey
- [x] Create tickets for any tasks or touchpoints not already defined
- [x] Update [Miro sketches](https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764536859308772&cot=14):
  - [x] Short oracle profile which can be embedded in markets on console, and new market and update market proposals on the token site
  - [x] Long oracle profile, showing all oracle details, which can be navigated to from the short profile (could be a popover, the oracle page in block explorer, or another solution)
  - [x] Console: show negative statuses in the market list
  - [x] Any other touchpoints defined above
- [x] Jon to arrange a kick-off with Matt and Dex
- [x] Neil to brief Joelle
- [ ] Visual design
  - [x] Short oracle profile
  - [x] Long oracle profile
  - [x] Console: Warning banner
  - [ ] Console: Market lists
  - [ ] Any other touchpoints defined above
- [ ] Stakeholder review and design critique of the visual design
- [ ] Update the tickets listed below with links to the visual design

## Sketch
- [Miro exploration](https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764536859308772&cot=14)
- [Journey: submitting and editing an oracle profile](https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764540284994519&cot=14)

### Process
- https://github.com/vegaprotocol/frontend-monorepo/issues/2136
- https://github.com/vegaprotocol/frontend-monorepo/issues/2135

### Console
- https://github.com/vegaprotocol/frontend-monorepo/issues/3224
- https://github.com/vegaprotocol/frontend-monorepo/issues/2086
- https://github.com/vegaprotocol/frontend-monorepo/issues/3225
- https://github.com/vegaprotocol/frontend-monorepo/issues/3227
- https://github.com/vegaprotocol/frontend-monorepo/issues/3228

### Governance
- https://github.com/vegaprotocol/frontend-monorepo/issues/2087

**Comment by joellecharlotte** [comment]
The proposed designs for Oracles Profile, Proofs + Details can be found in the Governance Figma file, with this user flow starting on the Proposals Detail page: [Figma link ↳](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=2502%3A12268&t=U4WmgcydlTw2i3nf-1)
