### ISSUE TITLE
🧑‍⚖️ Contributor code of conduct for governance

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#8]
## Story

As a governance participant 
I want to understand that there is a code of conduct and it's not just a wild west
So that I can trust in the quality of governance and community interactions, and know how to behave myself 

## Acceptance Criteria

- [ ] There's a way to access / view the code of conduct from governance lifecycle content (.xyz, forum?, docs) 
- [ ] We've thought through where this might also be relevant anywhere else ... and added relevant linking / call out(s)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

![Image](https://user-images.githubusercontent.com/47143694/190927133-38b96281-dea4-48ca-8732-19b2b51bd1c2.png)
