### ISSUE TITLE
Who is our target audience? (Just tidy up the outcomes)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/ux-and-visual-design#80]
## Challenge 

![Image](https://user-images.githubusercontent.com/46783148/204513388-26ee0d99-36e2-4bc1-a37a-11bd3a280738.png)

## Tasks

- [X] Agree brief and approach with Rebecca, Barney, Ramsey, Lewis?
- [ ] Update summary slides
- [ ] Check with Dave Mac how we can best share it internally (i.e. for onboarding)

**Comment by JonRay15** [comment]
This was done
