### ISSUE TITLE
Create a new site-preview image for Vega documentation site.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/ux-and-visual-design#85]
## The Chore

When you link to the docs site from discord twitter etc it grab an image from the site e.g.

<img width="480" alt="Screenshot 2022-12-01 at 16 14 44" src="https://user-images.githubusercontent.com/13255539/205103713-d4d18683-302c-4f46-b56e-72cbc6c18899.png">

I've just made a [changed](https://github.com/vegaprotocol/documentation/pull/407) to the docs site to improve the text. This to improve the image.

Here is an example from another site

<img width="657" alt="Screenshot 2022-12-01 at 16 18 19" src="https://user-images.githubusercontent.com/13255539/205104941-2f0b82d7-4e79-4d69-8fe8-0de4fbb90f89.png">

## Tasks

- [ ] Create an image
- [ ] Check with Candida
- [ ] add it to the site or create ticket to do so

**Comment by bigfandavid** [comment]
Proposed design.

![Image](https://user-images.githubusercontent.com/113683891/211518865-949b96b7-6459-465d-a4fa-c02406667024.jpg)

**Comment by edd** [comment]
Oh that `${siteconfig.tagline}` is back. Argh. It's a linter (prettier iirc) adding a line break in the wrong place. I will ticket this / reopen the old ticket.

**Comment by bigfandavid** [comment]
![Vega Docs Preview Image](https://user-images.githubusercontent.com/113683891/211835011-3aabe40a-1190-4967-ae16-8a3c46600e7d.jpg)

Updated, signed-off design.

**Comment by candida-d** [comment]
Looks great @bigfandavid, thank you!

**Comment by pennyandrews** [comment]
New ticket created for this to be implemented in the docs site here https://github.com/vegaprotocol/documentation/issues/450
