### ISSUE TITLE
Link to oracle files from market info

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/ux-and-visual-design#90]
## Story

As a trader interested in entering a market
I want evidence of the market oracle's reputation
So I can decide if it is trustworthy

## Acceptance Criteria

- [ ] I can find a link to oracle profile information

## Tasks

- [ ] Build a library to confirm the presence of an oracle file in the well-known repo, leaving scope to expand this repo to fetch and parse the contents of the file in future
- [ ] If an oracle spec file is present in the repo, add a link (titled "Oracle information") to it in the existing oracle section of the market info accordion (if there is no oracle file, do not show the link)
- [ ] Move the oracle info up to the third slot in the market info accordion, after "Key details" and "Instrument"
- [ ] QA

## Sketch
![image](https://user-images.githubusercontent.com/1080322/225942306-ca02cbb4-d509-401d-8605-f2fbeb8eaeaf.png)

## Additional details / background info
- Epic: https://github.com/vegaprotocol/ux-and-visual-design/issues/79
- Oracle profiles will be located in the repo here: https://github.com/vegaprotocol/well-known/tree/main/oracle-providers
