### ISSUE TITLE
SPIKE: Governance Transfers

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#93]
## The Spike

As a Frontend Team at Vega
We want to understand the **Governance Transfers** feature that core are developing and build a shared understanding of the implications / opportunities this feature creates for our user journeys and ultimately frontend applications 
So that we can agree on, plan and execute the work effectively

## How we'll know we're done

- [x] A cross section of frontend (UX, Dev, QA) are up to speed with the feature that is being developed by Core
- [x] We have a x-function / platform agreement on what this feature will enable for our users from a frontend perspective across all of our apps and tools (and at a high level, how)
- [x] We have a clear agreement on relative priorities / sequences for these features
- [x] We have established a way to stay in regular communications with the Core Feature Team in order to:
    - Have visibility of progress
    - Understand and track dependencies
    - Collaborate on key technical directions / decisions that impact our ability to deliver the agreed features in the FE  

## Tasks

- [x] Assign 1 UX, 1 Dev and 1 QA as the team to collaborate on this spike (who will then become the experts in this feature for the frontend team)
- [x] Team reads the spec and all other background reading (below)
- [x] Team is given an initial brief from the core feature team to understand the potential implications / opportunities 
- [x] Team sketches out a hypothesis of the user journeys / features this core feature represents for frontends (including the relative priorities / sequencing) https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764556957648950&cot=14
- [x] Team presents the hypothesis and facilitates a discussion around it with the core feature team, FELT and ELT 
- [x] Team refines further the hypothesis and shares with the wider business on Slack for input and feedback
- [x] Team finalises and breaks the work down into tickets for the appropriate project teams boards
- [x] Team defines and shares a target delivery plan that would enable the feature to be delivered in line with the core plan
- [x] Combined team has established how they will track progress, review work together and coordinate efforts as needed as we head towards deployment 1 

## Background Reading

- [Core Roadmap Feature Ticket](https://github.com/vegaprotocol/roadmap/issues/61)
- [Frontend Roadmap Feature Ticket](https://github.com/vegaprotocol/roadmap/issues/61)
- [Core Feature Spec](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0028-GOVE-governance.md#5-transfers-initiated-by-governance-post-oregon-trail) 
- Core Feature Team:
    - Zohar + Paul
- List of core tickets:
  - [All core dev or feature test issues](https://github.com/vegaprotocol/vega/issues?q=label%3Agovernance+label%3Atransfers)
    - [All core dev or feature test PRs](https://github.com/vegaprotocol/vega/pulls?q=label%3Agovernance+label%3Atransfers)
  - [All system test dev issues](https://github.com/vegaprotocol/system-tests/issues?q=label%3Agovernance+label%3Atransfers)
  - [Protos and API PR](https://github.com/vegaprotocol/vega/pull/7466)

**Comment by pennyandrews** [comment]
Update from Gordon 15th June:

Hey, so there is an entry for gov transfers in the master branch of the specs repo that is out-of-date to whats in the (correct/latest) cosmicelevator milestone branch, here are a couple of PRs to tidy up:
https://github.com/vegaprotocol/specs/pull/1766 (for the change to master)
https://github.com/vegaprotocol/specs/pull/1767 (to remove bumf from the title in cosmic)
Once these features go to mainnet the relevant spec content will be ported over to the master branch

**Comment by pennyandrews** [comment]
Slack thread for wider async sharing and feedback https://vegaprotocol.slack.com/archives/C8WS7M50E/p1686828059520239
