### ISSUE TITLE
SPIKE: Iceberg Orders

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/ux-and-visual-design#96]
## The Spike

As a Frontend Team at Vega
We want to understand the **Iceberg Orders** feature that core are developing and build a shared understanding of the implications / opportunities this feature creates for our user journeys and ultimately frontend applications 
So that we can agree on, plan and execute the work effectively

## How we'll know we're done

- [x] A cross section of frontend (UX, Dev, QA) are up to speed with the feature that is being developed by Core
- [x] We have a x-function / platform agreement on what this feature will enable for our users from a frontend perspective across all of our apps and tools (and at a high level, how)
- [x] We have a clear agreement on relative priorities / sequences for these features
- [x] We have established a way to stay in regular communications with the Core Feature Team in order to:
    - Have visibility of progress
    - Understand and track dependencies
    - Collaborate on key technical directions / decisions that impact our ability to deliver the agreed features in the FE  

## Tasks

- [x] Assign 1 UX, 1 Dev and 1 QA as the team to collaborate on this spike (who will then become the experts in this feature for the frontend) team)
- [x] Team reads the spec and all other background reading (below)
- [x] Team is given an initial brief from the core feature team to understand the potential implications / opportunities 
- [x] Team sketches out a hypothesis of the user journeys / features this core feature represents for frontends (including the relative priorities / sequencing) 
- [x] Team presents the hypothesis and facilitates a discussion around it with the core feature team, FELT and ELT 
- [x] Team refines further the hypothesis and shares with the wider business on Slack for input and feedback
- [x] Team finalises and breaks the work down into tickets for the appropriate project teams boards
- [x] Team defines and shares a target delivery plan that would enable the feature to be delivered in line with the core plan
- [x] Combined team has established how they will track progress, review work together and coordinate efforts as needed as we head towards deployment 1 

## Tickets

For all tagged tickets see the [X-Platform-UX Delivery board](https://github.com/orgs/vegaprotocol/projects/110/views/74)

### Console
- https://github.com/vegaprotocol/frontend-monorepo/issues/4095
- https://github.com/vegaprotocol/frontend-monorepo/issues/4096
- ~~https://github.com/vegaprotocol/frontend-monorepo/issues/4097~~
- https://github.com/vegaprotocol/frontend-monorepo/issues/4098

### Block explorer
- https://github.com/vegaprotocol/frontend-monorepo/issues/4108

### Docs
- https://github.com/vegaprotocol/documentation/issues/632

## Background Reading

- [Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764556399815278&cot=14)
- [Core Roadmap Feature Ticket](https://github.com/vegaprotocol/roadmap/issues/62)
- Frontend Roadmap Feature Ticket (TBC)
- Core Feature Spec is captured in the SLA spec PR:
  - https://github.com/vegaprotocol/specs/pull/1685
- Core Feature Team:
    - Will and Muthu
- List of core tickets:
  - https://github.com/vegaprotocol/vega/issues/8374
  - https://github.com/vegaprotocol/vega/issues/8370
  - https://github.com/vegaprotocol/vega/issues/8361
  - https://github.com/vegaprotocol/vega/issues/8359
  - https://github.com/vegaprotocol/vega/issues/8301
  - https://github.com/vegaprotocol/system-tests/issues/2111 (QA)
  - [Protos PR](https://github.com/vegaprotocol/vega/pull/8360) 
  - [GQL updates PR](https://github.com/vegaprotocol/vega/pull/8436)

**Comment by pennyandrews** [comment]
Adding link to yesterday's Core demo where Will did a lovely demo of Iceberg orders that would be useful for everyone to have a watch of if they missed it https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1686243069019449

**Comment by bwallacee** [comment]
Link to our questions and answers we have had so far: https://www.notion.so/vegaprotocol/Iceberg-Orders-32773e9c28ca4b10a070eadaf2325a46?pvs=4

**Comment by pennyandrews** [comment]
Slack thread for wider async sharing and feedback https://vegaprotocol.slack.com/archives/C8WS7M50E/p1686839068648029
